version: '3.8'
services:
  maven_app:
    image: ayo_project_maven_app:latest
    privileged: true
    user: root
    ports:
      - 80:8081
      - 443:443
    container_name: mavenApp
    volumes:
      - ~/tomcat:/usr/local/tomcat/logs